# Notice: This template has only been tested 
# under Python27 + GAE standard environment
application: vigilant-card-184220 
version: 1
runtime: python27
# threadsafe is required but can be either true or 
# false. For some package, it should be true e.g. Flask
threadsafe: false
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /.* 
  script: doIt.app 
  

libraries:
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.1.1"
- name: ssl
  version: 2.7
  





